### ISSUE TITLE
Please release the utility for macOS

### ISSUE THREAD

**Issue by m-emelchenkov** [KasperskyLab/triangle_check#8]
Please make a release of this utility for macOS.

**Comment by igosha-kl** [comment]
Unfortunately, that wouldn't work as good as on other platforms because of the binary signing requirements introduced in the recent versions of macOS.

**Comment by igosha-kl** [comment]
Pyinstaller doesn't work out of the box because libraries shipped along are not signed - closing until there is a good solution
